export const writeup = {
  slug: "fail-closed-deployments",
  title: "Why our deployments refuse to start",
  dek: "On Grantfox we made a set of misconfigurations impossible to run in production by having the process crash at boot instead of degrading quietly.",
  readTime: "5 min",
  body: [
    "We contribute to Grantfox, a wallet-native AI-prompt and agent marketplace built on Stellar, as outside contributors working against its live NestJS backend and Next.js frontend. A chunk of that work has had nothing to do with features. It has been going through the boot sequence and asking, for every environment variable that changes security behavior, what happens if this is simply left unset in production. In several places the honest answer was: the app starts anyway, using a default that was fine for a laptop and dangerous on a server.",
    "The clearest case was JWT_SECRET. Token-based auth is only as strong as the secret used to sign and verify tokens; anyone who holds that secret can mint a token claiming to be any user, because the server has no way to tell a self-issued token from one it issued itself. The backend used to fall back to a published dev-secret when JWT_SECRET wasn't set. That string exists in source history and local setup docs, which means it isn't a secret at all — it's a known value. A service running with it in production isn't weakly protected, it's unauthenticated, just with extra steps: forge a token with the well-known key, sign it, present it, and the app has no basis to refuse it.",
    "The fix was to stop tolerating the absence of JWT_SECRET once the app believes it's running for real. On boot, the app reads its environment mode, and outside of development it now requires JWT_SECRET to be explicitly set or it refuses to start. No fallback, no warning-and-continue. This is a deliberate trade: we gave up the convenience of it just runs in whatever environment someone forgot to configure, in exchange for a guarantee that a production process is never quietly running with a key an attacker can look up. A crash at deploy time is loud, immediate, and blocks the rollout. A silent fallback is invisible until someone finds it.",
    "The same pass turned up a second category that looks unrelated but isn't: PAYMENT_SIMULATION_ENABLED, MOCK_PAYMENT_ENABLED, MOCK_PAYMENT_FAIL, and DB_SEED_ON_STARTUP. Each of these exists for a real reason — you want to exercise the purchase flow without touching Stellar, or without a payment provider in the loop, or with a reproducible dataset when a fresh environment boots. The seed flag in particular writes a fabricated wallet with a 450-credit balance so there's something to test against. None of that is a problem in development. It becomes a problem the instant it's still on in a deployment real users can reach.",
    "We treat a seeded balance and a mocked payment success as the same failure mode, because structurally they are. Once that 450-credit wallet is written to the database, nothing downstream can tell it apart from a balance that arrived through an actual purchase — the wallet, transaction, and purchase code paths all read from the same tables and don't carry a provenance flag saying this credit was invented. A mock-payment flag left on has the identical property: it makes the purchase flow report success without money having moved, and that success is indistinguishable from a real one to everything reading it afterward. Fabricated state is fabricated state regardless of which flag produced it, so real deployments now refuse to start if any of these four are enabled, the same way they refuse to start without JWT_SECRET.",
    "The mechanism in both cases is the same shape: gate the unsafe behavior on the environment the process believes it's in, and make the gate fail closed rather than fail open. Fail open means an unset or misconfigured variable quietly resolves to assume dev, assume it is fine — which is exactly the setting where nobody is watching for it. Fail closed means the same missing configuration resolves to refuse to run, which turns a subtle security gap into an obvious, unmissable deploy failure. We'd rather have an engineer stare at a crashed boot log and set the right variable than have that gap sit live for however long it takes someone to notice.",
    "The general lesson we keep relearning is that developer-experience defaults and production-safety defaults are usually not the same value, and code that doesn't distinguish the two environments will eventually pick the convenient one at the worst time. It's cheaper to make that distinction explicit at process startup — one check, one place, fails loud — than to rely on every deployment being configured correctly by hand and hope the difference never matters.",
  ],
};
