// Grounded in the battery-storage reporting engagement described in
// research/VERIFIED_FACTS.md. Client name is intentionally withheld.
// Every number in this file is one we were given — nothing here is estimated.

export const writeup = {
  slug: "llm-grounding",
  title: "Teaching an LLM where the facts end",
  dek: "On a grid-scale battery reporting pipeline, we let an LLM write the sentences and never the numbers — then checked every number it wrote anyway.",
  readTime: "6 min read",
  body: [
    "We built the daily performance report for a grid-scale battery energy storage system the same way we'd build any reporting pipeline, right up until the last step. SCADA data comes off the site, a Python KPI engine turns it into the numbers that matter — state of charge, charge and discharge cycles, availability, whatever the contract calls for — and those numbers get frozen into a fact set before anything else happens. The last step is prose: someone has to turn a table of KPIs into a report a human wants to read. That's the step we handed to an LLM, and it's also the step we trust the least, which is why the whole pipeline is built around not trusting it.",

    "The design choice underneath all of this is that the LLM never computes anything. It doesn't sum a column, doesn't average a week, doesn't derive a percentage from two numbers we gave it. Every number that appears in the final report was computed by the Python KPI engine, full stop, before the LLM ever sees the data. The model's job is strictly narration: given this frozen set of facts, write paragraphs a plant operator would want to read. That split matters because a deterministic KPI engine is testable in the normal sense — same input, same output, every time — and an LLM asked to also do arithmetic under the hood is neither deterministic nor, in our experience, reliably correct at it. So we don't ask it to. We ask it to write, and we let code do the only part of the job where being wrong is silent and expensive.",

    "'Frozen fact set' is doing real work in that sentence, not just sounding careful. It means the KPI engine's output is locked before the LLM is invoked — a fixed structure of numbers and labels that the model is given as context and cannot revise, recompute, or extend. The LLM can choose how to phrase a number, what order to present it in, which numbers to foreground for a given day's story, but it cannot introduce a number that isn't already sitting in that frozen set. If the model wants to say the system discharged for some number of hours, that figure has to already exist in the facts it was handed. Nothing downstream of the KPI engine gets to invent a fact.",

    "That constraint only matters if something enforces it, so after the LLM writes its draft, a separate grounding check reads the output back. Mechanically, it's straightforward: pull every numeric token out of the generated text — every figure, percentage, and count the model wrote down — and match each one against the frozen fact set. A number in the LLM's prose that isn't traceable to a number Python actually computed is a mismatch. It doesn't matter if the mismatch is a hallucinated statistic or a plausible-looking rounding of a real one that drifted in the retelling — either way, it's a number in the report that didn't come from the data, and that's exactly the failure mode this pipeline exists to catch. One unmatched numeric token anywhere in the output blocks that report from being published. Not flagged for review, not published with a caveat — blocked.",

    "We treat the grounding check as load-bearing enough that it needs its own test coverage, not just spot-checks against a few sample reports. The pipeline as a whole is backed by 648 tests, and none of them make a network call — the KPI math, the fact-freezing step, and the grounding check itself are all exercised deterministically, offline, on every run. That's a direct consequence of keeping computation and narration separate: the parts of the system that are the easiest to get catastrophically wrong (arithmetic on real energy and financial figures) are also the parts that are cheapest to test exhaustively, because they don't depend on what an LLM feels like producing that day.",

    "None of that protects you from the report simply not showing up. A pipeline that correctly refuses to publish a bad report is only half the story if nobody notices the report never ran at all — a stalled cron job and a rock-solid grounding check produce the same silence from the client's point of view. So there's a monitoring layer alongside the reporting logic: a dead-man's-switch check that expects a scheduled run to happen and raises an alert the moment one doesn't. Correctness and liveness are different failure modes, and we didn't want a fix for one to quietly stand in for the other.",

    "We didn't build it this way because LLMs are untrustworthy in some abstract sense — we built it this way because we were putting model output next to numbers a client would use to make real operating and financial decisions about a real physical asset, and 'usually right' isn't a property you can hand someone in that position. Anyone shipping LLM-generated text alongside numbers that matter is making the same bet whether they've named it or not: either the model's arithmetic is trusted implicitly, or something outside the model checks its work before a human sees it. Keeping the LLM out of the computation entirely, freezing the facts before it writes a word, and verifying every number it emits against that frozen set afterward isn't a hedge against a model being bad at math. It's a refusal to let a step we can't fully verify be the one deciding what the numbers are.",
  ],
}
