// Every claim in this file must trace to a row in `research/VERIFIED_FACTS.md`.
// If you can't point at the source, don't add the line.

export const writeup = {
  slug: "verified-claims-ledger",
  title: "A ledger for every claim we publish",
  dek: "Why the sentence 'not yet disclosed' on this site and the field UNAVAILABLE in Grantfox's wallet API are the same engineering decision.",
  readTime: "5 min read",
  body: [
    "Every public claim on this site is supposed to trace back to a named source — a repository, a commit, a screenshot, a README — not to our own recollection of what we built. We keep that trace in a ledger: a plain document that pairs each sentence we publish with where it came from and when we checked it. If a claim can't point at a row in that ledger, it doesn't ship. That sounds like a documentation habit. It's actually the same decision we make inside the software itself, and the clearest place to see it is a single API response inside Grantfox.",
    "Grantfox is a wallet-native marketplace for AI prompts and agents, built on Stellar, and we work on its backend and frontend as outside contributors. A wallet there carries two different kinds of balance: a ledger balance the backend can compute directly from the purchases and transactions it has recorded, and an on-chain balance that would require actually reading the Stellar network. We haven't integrated that on-chain read yet. The honest state of that piece of the system is: we don't know the number.",
    "The easy way to handle that gap is to fake it — return the ledger figure and label it the on-chain balance, or compute something plausible-looking and let the wallet screen render it like any other field. Nobody inspecting the JSON would necessarily catch it, and a dashboard where every field has a number looks more finished than one with a visible gap. We didn't do that. The API reports on-chain balance as UNAVAILABLE. Not zero, not an estimate, not the ledger number wearing an on-chain label — an explicit status that says the verification path doesn't exist yet.",
    "Transaction hashes get the same treatment. A real Stellar transaction hash is a 64-character hex string, and Grantfox populates that field only when one actually exists on-chain. When it doesn't — a transaction hasn't settled, or the flow in question doesn't produce one — the field is null. We could have shipped a placeholder, something hex-shaped that fills the field and satisfies whatever the frontend expects a string to look like there. We didn't, for the same reason the balance isn't estimated: a null is a true statement about what we know, and a fabricated hash is a lie wearing the shape of proof.",
    "Neither of those is a large decision. They're easy to miss in a diff, and no user is likely to ever ask why one wallet field says UNAVAILABLE while the rest show numbers. But they're the same decision, applied at the level of an API field instead of the level of a sentence, that governs what we let onto this site. An UNAVAILABLE status and a not yet disclosed label are the same move: when the honest answer is we don't have that number, say so instead of computing something that resembles it.",
    "That's why we don't publish Grantfox's fee or commission percentage anywhere on this site. We could estimate one from typical marketplace terms, or infer a range from the parts of the fee logic we've reviewed directly, and it would sit comfortably next to everything else in a services page. We label it not yet disclosed instead, because we don't have a source for it the way we have a source for the deployment hardening we shipped or the purchase flow we built. The same rule that keeps a null in the transaction-hash field keeps that line out of our copy.",
    "The cost is visible in both places. A wallet screen with UNAVAILABLE in it looks less finished than one where every field carries a number. A services page with not yet disclosed in it makes a flatter pitch than one with a fee percentage and a revenue projection sitting next to the rest of the numbers. Neither of us gets to pretend the gap isn't there just because filling it would read better. The alternative — inventing the missing piece — is cheap exactly once, and it's the same failure whether it surfaces as a fabricated wallet balance or a fabricated statistic on our own site.",
    "So the ledger isn't a disclaimer we bolt on after the fact to cover ourselves. It's the same discipline we build into the systems we ship, running in reverse on our own claims: before a sentence goes on this site, we ask what row backs it, the same way Grantfox's balance endpoint asks whether it actually has an on-chain read before it prints a figure. When the answer is no, the sentence — like the field — says so.",
  ],
}
